/**
 * This file is automatically generated by the mvr SDK.
 * You can edit this file, but it will be overwritten on the next run.
 * You should check this file in your version control system.
 *
 * Run this script before building your project to ensure that the mvr.ts file stays up to date.
 *
 * You can use this pre-built cache when initializing your Sui client by calling
 * `getMvrCache("mainnet")` or `getMvrCache("testnet")` and passing it as the `overrides` option.
 */

const mainnetResolution = {
  packages: {
    "@suins/payments":
      "0x863d5f9760f302495398c8e4c6e9784bc17c44b079c826a1813715ef08cbe41a",
    "@mvr/demo":
      "0xf388e75a4ed8c7eb7aff4337a058c7949f5b426a58e586bf6e12785b99c03e31",
    "@suins/coupons":
      "0xb162340524e0697461c307b9dc530c17e837b0f2c6d7f787da40d29d29681e5e",
    "@mysten/payment-kit":
      "0xbc126f1535fba7d641cb9150ad9eae93b104972586ba20f3c60bfe0e53b69bc6",
    "@suins/discounts":
      "0x03f625d805339b1b0235ba8c503fa6ea62c88c02ddf14cd9d246d9e1febc0c76",
    "@suins/core":
      "0x71af035413ed499710980ed8adb010bbf2cc5cacf4ab37c7710a4bb87eb58ba5",
    "@mvr/metadata":
      "0xc88768f8b26581a8ee1bf71e6a6ec0f93d4cc6460ebb66a31b94d64de8105c98",
    "@mvr/core":
      "0xbb97fa5af2504cc944a8df78dcb5c8b72c3673ca4ba8e4969a98188bf745ee54",
    "@pkg/qwer":
      "0x1d680c0a5bf2f0a875acb4679dc2bc660bf10052292fdfdac274e8b967bd045a",
    "@deepbook/core":
      "0x337f4f4f6567fcd778d5454f27c16c70e2f274cc6377ea6249ddf491482ef497",
  },
  types: {
    "@pkg/qwer::mvr_a::V1":
      "0xc168b8766e69c07b1b5ed194e3dc2b4a2a0e328ae6a06a2cae40e2ec83a3f94f::mvr_a::V1",
    "@pkg/qwer::mvr_b::V2":
      "0x01dcc0337dfe29d3a20fbaceb28febc424e6b8631e93338ed574b40aadc2a9ea::mvr_b::V2",
    "@mvr/metadata::package_info::PackageInfo":
      "0x0f6b71233780a3f362137b44ac219290f4fd34eb81e0cb62ddf4bb38d1f9a3a1::package_info::PackageInfo",
    "@mvr/core::app_record::AppRecord":
      "0x62c1f5b1cb9e3bfc3dd1f73c95066487b662048a6358eabdbf67f6cdeca6db4b::app_record::AppRecord",
    "@mvr/metadata::git::GitInfo":
      "0x0f6b71233780a3f362137b44ac219290f4fd34eb81e0cb62ddf4bb38d1f9a3a1::git::GitInfo",
  },
};
const testnetResolution = {
  packages: {
    "@mvr/metadata":
      "0xb96f44d08ae214887cae08d8ae061bbf6f0908b1bfccb710eea277f45150b9f4",
    "@suins/core":
      "0x40eee27b014a872f5c3330dcd5329aa55c7fe0fcc6e70c6498852e2e3727172e",
    "@deepbook/core":
      "0x22be4cade64bf2d02412c7e8d0e8beea2f78828b948118d46735315409371a3c",
    "@suins/discounts":
      "0x7976f9bfe81dcbdbb635efb0ecb02844cd79109d3a698d05c06ca9fd2f97d262",
    "@pkg/qwer":
      "0xbb2e63bbf8410d159c12126ee816f1299ded62fb7f4fe60c614498b748cf4bf3",
    "@mysten/payment-kit":
      "0x7e069abe383e80d32f2aec17b3793da82aabc8c2edf84abbf68dd7b719e71497",
    "@suins/coupons":
      "0x63029aae8abbefae4f4ac6c5e3e0021159ea93a94ba648681fd64caf5b40677a",
    "@suins/payments":
      "0x9e8b85270cf5e7ec0ae44c745abe000b6dd7d8b54ca2d367e044d8baccefc10c",
  },
  types: {
    "@mvr/metadata::package_info::PackageInfo":
      "0xb96f44d08ae214887cae08d8ae061bbf6f0908b1bfccb710eea277f45150b9f4::package_info::PackageInfo",
    "@pkg/qwer::mvr_b::V2":
      "0x6b991ed7e0164d0927df2eaf4fb075d528b4b86d6feee35711cf8d49f2538691::mvr_b::V2",
    "@pkg/qwer::mvr_a::V1":
      "0x077adfd262090b6645ea05087e252796a205d0369f165c99aa8147f3c678b579::mvr_a::V1",
    "@mvr/metadata::git::GitInfo":
      "0xb96f44d08ae214887cae08d8ae061bbf6f0908b1bfccb710eea277f45150b9f4::git::GitInfo",
  },
};

export function getMvrCache(network: "mainnet" | "testnet") {
  return network === "mainnet" ? mainnetResolution : testnetResolution;
}
